[glsl-in] Add support for texture function with LOD bias
gfx-rs/naga pull request #1051
Opened 2021-06-30 17:09 UTC by magcius

2021-06-30 18:50 UTC, JCapucho requested changes
We can write this in more idiomatic rust

2021-06-30 18:50 UTC, JCapucho commented on src/front/glsl/functions.rs
> -                        if args.len() != 2 {
You can write this as
```rust
if !(2..=3).contains(&args.len()) {
  return Err(ErrorKind::wrong_function_args(name, 2, args.len(), meta));
}
```

2021-06-30 18:50 UTC, JCapucho commented on src/front/glsl/functions.rs
> +                        };
You can write this as
```rust
args.get(2).map(SampleLevel::Bias).unwrap_or(SampleLevel::Auto);
```

2021-06-30 23:14 UTC, magcius commented
Thank you! Still getting used to idiomatic Rust

2021-07-01 01:45 UTC, JCapucho approved these changes
Looks good now, thank you for your contribution.

2021-07-01 01:45 UTC, merged