Avoid case fallthrough when last statement is break, continue, kill or return
gfx-rs/naga pull request #1392
Opened 2021-09-17 21:01 UTC by DDoS

Naga is generating `break; fallthrough;` statements at the end of each case for any switch statement in my shaders (SPIR-V compiled from GLSL). The tint WGSL compiler used by Chromium rejects these shaders because the `fallthrough;` statement is obviously unreachable code. These changes prevent generating a `fallthrough` when the last statement of the case body always exits the switch.

I've never written Rust before, let me know if this idiomatic code.

2021-09-17 21:08 UTC, JCapucho requested changes
Thank you for your contribution, there are just some styling fixes nothing major

2021-09-17 21:08 UTC, JCapucho commented on src/front/spv/function.rs
> +                                            Some(&crate::Statement::Return { value: _ }) => false,
You can replace `value: _` with `..`

2021-09-17 21:08 UTC, JCapucho commented on src/front/spv/function.rs
> +                                            Some(&crate::Statement::Kill) => false,
Instead of doing
```rust
arm => false,
arm => false,
arm => false,
```
You can do
```rust
arm | arm | arm => false
```

2021-09-17 21:58 UTC, DDoS commented
I made the requested changes. Is there a way to auto format the code?

2021-09-17 22:01 UTC, JCapucho commented
you should be able to run `cargo fmt` in the terminal

2021-09-20 11:52 UTC, DDoS commented
Running  `cargo fmt` only changed the file `src/front/glsl/builtins.rs`, so I assume my code is already correctly formatted.

2021-09-20 14:11 UTC, JCapucho approved these changes
lgtm

2021-09-20 14:11 UTC, merged