Refactor namer scheme, fix trailing digits
gfx-rs/naga pull request #1510
Opened 2021-11-03 18:08 UTC by kvark

Fixes #1508

2021-11-04 04:36 UTC, jimblandy requested changes
At present, `namer.call("!@#$")` and `namer.call("")` both return `""` the first time. We should check for an empty sanitized string. Then we can drop the check in `call_or`.

It took me a while, but I eventually convinced myself that this will always produce distinct names. I don't object to landing this (with the above fixed), but I think it would be much simpler if we just ensured that `sanitize` never returns anything ending in `_N`. Then we can simply say, `self.unique` never contains anything ending in `_N`, so either we just added the string, or we added a novel numeric suffix.

2021-11-05 03:16 UTC, kvark commented on src/proc/namer.rs
> +                if base.ends_with(char::is_numeric) || self.keywords.contains(base.as_ref()) {
right, I'll add an assert at least

2021-11-05 15:21 UTC, jimblandy approved these changes

2021-11-09 14:24 UTC, merged

2021-12-02 03:19 UTC, kvark commented
Published in 0.7.2