[spv-out] Fix scalar-times-matrix operations
gfx-rs/naga pull request #1524
Opened 2021-11-12 17:42 UTC by parasyte

Converting some GLSL to WGSL, I ran into a panic in the SpirV backend: `not implemented: Mul (Scalar, Matrix)`. The fix is super simple. Tests are included.

Interesting, the HLSL backend already does this same transformation. Cool!

2021-11-12 17:45 UTC, parasyte commented
The MSL validation error is interesting. Can anyone provide pointers on that?

2021-11-13 18:06 UTC, kvark requested changes
Thank you for the PR!

2021-11-13 18:06 UTC, kvark commented on tests/in/scalar-times-matrix.wgsl
> +[[stage(vertex)]]
let's not have a separate test file for each operation, instead put it into `operations.wgsl`

2021-11-13 22:45 UTC, parasyte commented
@kvark I've addressed your feedback. Thanks for the review!

2021-11-15 00:07 UTC, kvark approved these changes
thank you!

2021-11-15 00:07 UTC, merged