[hlsl-out] fix matrix not being declared as transposed
gfx-rs/naga pull request #1784
Opened 2022-03-20 14:07 UTC by teoxoy

HLSL uses inverted col/row notation (relative to GLSL, WGSL, MSL).

i.e. `mat3x2` in WGSL = `float2x3` in HLSL

Reference: [HLSL Matrix Doc](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-matrix)

2022-03-21 02:31 UTC, cwfitzgerald commented
I'm confused, this PR appears to be making the hlsl declaration types be the same as wgsl, with column first and then row, but the comments and the PR say that it should be inverted.

2022-03-21 08:56 UTC, teoxoy commented
HLSL's matrix type is of the form `matRxC`

matrix type in GLSL/WGSL/MSL is of the form `matCxR`

So passing column first, row second, to HLSL will cause the matrix to be the transposed version of the original.

2022-03-21 16:34 UTC, teoxoy commented
Before this PR, trying to change the access test as in https://github.com/gfx-rs/naga/pull/1784/commits/0d920f508f83d0611e8fe501aeab64fc39e9815d and passing the resulting HLSL code trough DXC results in the error below

![hlsl_fail](https://user-images.githubusercontent.com/28601907/159308556-fda1026c-f0a0-40cc-a699-1dd485b1ab2f.png)

With the fix in this PR this no longer happens.

2022-03-21 17:01 UTC, cwfitzgerald requested changes
One comment, but otherwise looks okay

2022-03-21 17:01 UTC, cwfitzgerald commented on src/back/hlsl/storage.rs
> +                let (rows, columns) = (columns, rows);
I think this is confusing, I'd much rather just flip the usages everywhere

2022-03-21 23:36 UTC, kvark commented
Thank you for the PR!
We need to take a bit of extra thought to review this, since we specifically output all matrices in buffers as row-major.
Our HLSL matrix logic is a bit non-trivial. Maybe it's a good chance to try to document it thoroughly in the code (i.e. at the top of the module) and understand clearly.

2022-03-21 23:53 UTC, teoxoy commented
No problem.

Regarding documentation, there is already this nicely written note

https://github.com/gfx-rs/naga/blob/05f050fad485763bf7bf6e1ad4206007b52bc345/src/back/hlsl/mod.rs#L9-L21

is there anything else you'd like me to add?

2022-03-23 05:42 UTC, kvark commented
So to me this comment reads like the current code is already correct, isn't it?

2022-03-23 09:27 UTC, teoxoy commented
> Finally because all of our matrices are transposed, if you use `mat3x4`, it'll become `float4x3` in HLSL.

This line is not right and what this PR is solving. `mat3x4` will become a `mat4x3` (GLSL/WGSL/MSL notation) but will become a `float3x4` in HLSL (due to HLSL's matrix notation being inverted already).

I fixed this doc line in this PR as well.

This whole thing is quite confusing and I got confused as well while trying to fix it.

2022-03-27 07:37 UTC, kvark commented
> This line is not right and what this PR is solving. mat3x4 will become a mat4x3 (GLSL/WGSL/MSL notation)

Sorry, I'm not following this. Here is the GLSL code for matrix type:
```rust
            TypeInner::Matrix {
                columns,
                rows,
                width,
            } => write!(
                self.out,
                "{}mat{}x{}",
                glsl_scalar(crate::ScalarKind::Float, width)?.prefix,
                columns as u8,
                rows as u8
            )?,
```
Clearly it makes it so `mat3x4` in WGSL becomes `mat3x4` in GLSL. I.e. there is no difference in notation. The only difference is with HLSL.

2022-03-27 09:28 UTC, teoxoy commented
Sorry I think I made my explanation more confusing than it should have been.

See quote below with `()` added by me.

> Finally because all of our matrices are transposed, if you use `mat3x4` (3 columns, 4 rows), it'll become `float4x3` (3 columns, 4 rows -> issue is here, not transposed) in HLSL.

2022-03-28 05:23 UTC, kvark approved these changes
Thanks for your patience!
I launched a small sanity test in https://github.com/gfx-rs/naga/runs/5714948153?check_suite_focus=true to see if the current algorithm produces invalid HLSL, and indeed that's the case.

2022-03-28 05:24 UTC, merged