wgsl-in, glsl-in: Short circuit || and &&
gfx-rs/naga pull request #2028
Opened 2022-08-15 23:06 UTC by adeline-sparks

Fixes #1931.

Clippy ignores are for 1.63, fixes for those are #2026.

2022-08-24 21:22 UTC, JCapucho requested changes
Disclaimer: only read the glsl code yet, so this might or might not apply to the wgsl frontend

There's an issue with your implementation, you're always branching on the left expression, this is true for `LogicalAnd` but not for `LogicalOr`, the latter must only execute the right hand side if it evaluates to `false`.

Also you seem to be creating the following pseudocode:
```
if (left) {
  local = right
} else {
  local = constant
}
```
you could instead do:
```
local = left
if (left) {
  local = right
}
```

2022-11-24 07:24 UTC, adeline-sparks commented
Looking at this again, I think it is translating things correctly. The tests show that for the `&&` case, the RHS is evaluated in the accept branch of the if statement, while for the `||` it is evaluated in the reject branch. 

I'll have a go at generating multiple assignments instead of single assignment. Would it be better to create a logical not and always leave the reject branch empty so that the generated code doesn't use an `else` in the `||` case?

2022-12-02 10:35 UTC, teoxoy commented
> Looking at this again, I think it is translating things correctly. The tests show that for the `&&` case, the RHS is evaluated in the accept branch of the if statement, while for the `||` it is evaluated in the reject branch.

Tests seem correct indeed, but quite verbose (see below).

> Would it be better to create a logical not and always leave the reject branch empty so that the generated code doesn't use an `else` in the `||` case?

I think so (as per @JCapucho's suggestion) because the extra assignments are redundant, we already know the var is true/false.

2023-10-25 23:52 UTC, cwfitzgerald commented
Hello, thank you for your PR against Naga!

As part of https://github.com/gfx-rs/wgpu/issues/4231, we have moved development of Naga into the wgpu repository in the Naga subfolder. We have transferred all issues, but we are unable to automatically transfer PRs. 

As such, please recreate your PR against the wgpu repository. We apologize for the inconvenience this causes, but will make contributing to both projects more streamlined going forward.

We are leaving PRs open, but once they are transferred, please close the original Naga PR.

2025-01-12 23:47 UTC, closed without merging