glsl-in: Perform output parameters implicit casts
gfx-rs/naga pull request #2063
Opened 2022-09-17 22:23 UTC by JCapucho

Rant: this is incredibly cursed and I wouldn't even believe this existed if I hadn't ran into a shader that used this.

Glsl defines under `Function Definitions` (Paragraph 6.1 in glsl 4.60),
the following:

> When function calls are resolved, an exact type match for all the arguments is sought.
> (...)
> If no exact match is found, then the implicit conversions in section “Implicit Conversions” will be applied to find a match.
> (...)
> Mismatched types on output parameters (out or inout) must have a conversion from the formal parameter type to the calling argument type.

The glsl frontend wasn't performing this implicit cast for output parameters.

They are now implemented trough a proxy write (like when swizzling for output parameters), where a spill variable with the correct type is passed and on the call prologue a conversion back to the original type is performed and the value stored in the original variable.

Furthermore if the variable in declared `inout`, a conversion is also made in the call prelude from the original type to the correct type and the value is stored in the spill variable.

2022-12-02 10:09 UTC, teoxoy approved these changes
> Rant: this is incredibly cursed and I wouldn't even believe this existed if I hadn't ran into a shader that used this.

That's indeed quite some magic the GLSL spec mandates 😅

2022-12-02 10:15 UTC, teoxoy commented
Looks like there are some test conflicts, feel free to merge once resolved.

2022-12-05 19:53 UTC, jimblandy requested changes

2023-01-17 22:47 UTC, JCapucho commented on src/front/glsl/functions.rs
> +                // from the definition argument to the calling argument.
It makes sense, it also highlighted a problem where only the out conversion was being checked, it should be fixed now

2023-02-02 21:51 UTC, jimblandy commented
It looks like the log message on commit e260a5c9 isn't right.

2023-02-03 14:29 UTC, JCapucho commented
> It looks like the log message on commit [e260a5c](https://github.com/gfx-rs/naga/commit/e260a5c983f0ebc864a77ae3e52c00176582b2b8) isn't right.

Oh no, seems like I did something that made git override the commit message with one of another commit that was merged by master (It also seems to have squashed commits 😞)

2023-02-03 14:41 UTC, JCapucho commented
@jimblandy should be fixed and rebased

2023-02-06 21:10 UTC, jimblandy approved these changes
This looks good to land.

2023-02-08 11:39 UTC, merged