Allow u32 textureStore coordinates
gfx-rs/naga pull request #2172
Opened 2022-12-13 05:12 UTC by PENGUINLIONG

As illustrated in https://www.w3.org/TR/WGSL/#texturestore:

> F is a [texel format](https://www.w3.org/TR/WGSL/#texel-format)
> C is [i32](https://www.w3.org/TR/WGSL/#i32), or [u32](https://www.w3.org/TR/WGSL/#u32)
> ...

So I guess `vec<u32>` should be a valid `textureStore` coordinate.

I saw that in `back::glsl::write_texture_coord` the coord is explicitly cast to `ivec` so I think that's good. Please remind me if anything should be changed accordingly in the codegens.

2022-12-16 17:11 UTC, teoxoy requested changes
I looked over the backends and this shouldn't cause any issues.
Could you add some lines to the `tests/in/image.wgsl` file to test for those overloads?

Thanks!

2022-12-19 13:37 UTC, teoxoy commented
This PR would in theory allow `textureLoad` to also accept `u32` coordinates. Could you also add a test for that?
Also, make sure you push the changed test snapshots (that's why CI is failing).

2022-12-22 10:06 UTC, teoxoy commented
Looks like we need to check for `component_kind == crate::ScalarKind::Uint` and convert `array_index_i32_id` to a uint (similar to how we do for the else branch below).

https://github.com/gfx-rs/naga/blob/8e1b0529e62f39f2051ec813f99fd682d1a43b5f/src/back/spv/image.rs#L317-L336

2022-12-22 10:54 UTC, PENGUINLIONG commented
ah thanks for the hint ;)

2022-12-22 11:29 UTC, PENGUINLIONG commented
wow thats funny. i thought the glsl back is not affected.

2022-12-22 11:48 UTC, PENGUINLIONG commented
Oof. Can I rerun the DXC test?

2022-12-22 14:14 UTC, teoxoy commented on src/back/glsl/mod.rs
> +                    write!(self.out, "ivec{}(", vector_size)?;
Let's do this only if necessary (i.e. only if the `coordinate` expression's type is unsigned).

2022-12-22 17:57 UTC, teoxoy approved these changes
Looks good! Thanks!

2022-12-22 17:59 UTC, merged