Fix wgsl out struct layout
gfx-rs/naga pull request #2450
Opened 2023-08-21 03:03 UTC by mikialex

fix https://github.com/gfx-rs/naga/issues/1803 by explicitly adding a size mark on all struct fields.

2023-08-21 04:22 UTC, mikialex commented
a test failed due to the two struct field members having the same offset. I think this should be checked in validation and fixed in another pr.

2023-08-31 17:59 UTC, teoxoy requested changes

2023-08-31 17:59 UTC, teoxoy commented on src/back/wgsl/writer.rs
> +            write!(self.out, "@size({current_field_size}) ")?;
We can avoid writing the size explicitly if it's the same as the one inferred. See example below on how to get the size:

https://github.com/gfx-rs/naga/blob/0491d39232bafc30962f6ea240ab6ed457282a62/src/back/msl/writer.rs#L3178-L3179

2023-10-25 23:49 UTC, cwfitzgerald commented
Hello, thank you for your PR against Naga!

As part of https://github.com/gfx-rs/wgpu/issues/4231, we have moved development of Naga into the wgpu repository in the Naga subfolder. We have transferred all issues, but we are unable to automatically transfer PRs. 

As such, please recreate your PR against the wgpu repository. We apologize for the inconvenience this causes, but will make contributing to both projects more streamlined going forward.

We are leaving PRs open, but once they are transferred, please close the original Naga PR.

2025-01-12 23:47 UTC, closed without merging