Add buffer pointer support for WGSL (SPV_EXT_physical_storage_buffer)
gfx-rs/naga pull request #2457
Opened 2023-08-25 19:20 UTC by felipeagc

This will add support for the `PhysicalStorage` SPIR-V storage class, which will enable use of the [VK_KHR_buffer_device_address](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_buffer_device_address.html) Vulkan extension.

Here's some example WGSL code for what this looks like:
```wgsl
struct Buffer {
    data: vec4<f32>,
}
struct PushConstants {
    buf: ptr<buffer, Buffer, 16>, // Pointed-to type must have 16-byte alignment
}
var<push_constant> pc: PushConstants;

// Accessing the buffer
var data = (*pc.buf).data;
```

The name of the WGSL address space is `buffer` and the third parameter for the pointer is the alignment of the pointed-to Buffer, which affects load operations on the buffer. It is optional and defaults to 16, as per the [GLSL spec](https://github.com/KhronosGroup/GLSL/blob/ad383324612d8493c78d52d0c903969fe1dddd0a/extensions/ext/GLSL_EXT_buffer_reference.txt#L139).

The size and alignment of pointers in this storage class is 8 bytes, so I also had to change that.

One thing this would allow for and that I did not implement is recursive pointers:
```wgsl
struct Buffer {
    data: f32,
    next: ptr<buffer, Buffer>,
}
```

2023-09-06 17:01 UTC, jimblandy requested changes
Thanks - this looks very interesting.

2023-09-06 17:02 UTC, jimblandy commented
@felipeagc Just out of curiosity - what are you using this new `Capability` for?

2023-09-09 22:43 UTC, felipeagc commented on src/valid/type.rs
> +                let data_flag = if let As::PhysicalStorage { .. } = space {
Added!

2023-09-09 22:44 UTC, felipeagc commented on src/valid/mod.rs
> +        /// Support for pointers to device buffers.
Added more information

2023-09-09 22:45 UTC, felipeagc commented on src/valid/type.rs
>                      Alignment::ONE,
Yeah, that looks wrong, but it was working fine without changing it here. Added the proper alignment just in case.

2023-09-09 22:46 UTC, felipeagc commented on src/proc/layouter.rs
> +                    alignment: Alignment::EIGHT,
Added 2 constants, for size and alignment.

2023-09-09 22:48 UTC, felipeagc commented on src/valid/type.rs
>                  // array elements, so we do not mark them as `DATA`.
Yes, I changed it and moved it to the else branch, though maybe the wording needs improvement.

2023-09-09 22:49 UTC, felipeagc commented on src/lib.rs
> +    /// Buffer device pointers.
Added relevant information.

2023-09-09 22:54 UTC, felipeagc commented
> @felipeagc Just out of curiosity - what are you using this new `Capability` for?

I'm writing a Vulkan renderer and wanted to use buffer pointers to simplify the design a bit. But since I was using naga to compile shaders, I needed to add the feature to the compiler! :)

I don't know if this kind of feature is too out of scope for naga, as far as WebGPU is concerned, but since I implemented it for myself I figured I should try to upstream it so other people can use it.

2023-10-25 23:49 UTC, cwfitzgerald commented
Hello, thank you for your PR against Naga!

As part of https://github.com/gfx-rs/wgpu/issues/4231, we have moved development of Naga into the wgpu repository in the Naga subfolder. We have transferred all issues, but we are unable to automatically transfer PRs. 

As such, please recreate your PR against the wgpu repository. We apologize for the inconvenience this causes, but will make contributing to both projects more streamlined going forward.

We are leaving PRs open, but once they are transferred, please close the original Naga PR.

2023-11-02 12:26 UTC, exrook commented
@felipeagc As I'm also interested in using these feature, I've rebased your PR branch on the post-merge wgpu repo here: https://github.com/exrook/wgpu/tree/buffer_pointer

2024-02-05 18:04 UTC, junglie85 commented
Hi. Just wondering what the status of this PR is as I’d like to use this feature too.

2025-01-12 23:47 UTC, closed without merging