[valid] Disallow NaNs and infinities
gfx-rs/naga pull request #2508
Opened 2023-09-25 17:15 UTC by teoxoy

WGSL doesn't currently allow NaNs and infinities.

Resolves https://github.com/gfx-rs/naga/issues/2461.

2023-09-25 17:41 UTC, jimblandy approved these changes
We should also document that `Literal::F32` and `Literal::F64` must not be nan or infinity.

2023-09-25 17:43 UTC, jimblandy requested changes
Sorry - could we also get some coverage in `tests/wgsl-errors.rs`?

2023-09-25 18:09 UTC, teoxoy commented
It's not possible to spell out NaNs or infinities in WGSL though.

I did run a manual test here: https://github.com/gfx-rs/naga/issues/2461#issuecomment-1734164109.

> We should also document that `Literal::F32` and `Literal::F64` must not be nan or infinity.

Should we? I keep going back and forth on what's best for IR documentation.
On the one hand we have code in the validator that enforces the invariants of the IR which is usually self-explanatory but sometimes quite involved.
On the other, it would be nice to see at a glance what those invariants are on the IR itself but I worry they will get out of sync or might be too lengthy.

In this case we'll also most likely get an extension + capability which will allow NaNs and infinities.
https://github.com/gpuweb/gpuweb/issues/2259 (SPIR-V has `SPV_KHR_float_controls`; haven't looked into the other languages).

2023-09-25 20:11 UTC, jimblandy commented
> It's not possible to spell out NaNs or infinities in WGSL though.

Oh, that's true. If this change were more involved I would want to imitate the unit tests from `analyzer.rs`, but it doesn't seem worth it. Maybe in the future we will be able to implement some coverage requirements!

> On the other, it would be nice to see at a glance what those invariants are on the IR itself but I worry they will get out of sync or might be too lengthy.

Yes, this is a risk. On the balance, though, I think it's really valuable to have the `lib.rs` docs be everything one needs to work with the IR. They're not there yet, but it's not too much trouble to avoid losing ground as we make new changes.

2023-10-05 19:50 UTC, jimblandy approved these changes

2023-10-05 19:50 UTC, merged