[msl-out] Make varyings' struct members unique
gfx-rs/naga pull request #2521
Opened 2023-09-28 15:42 UTC by evahop

Fixes #1490

Naming conflicts can occur when multiple structs get flattened into one varyings struct.
This moves the `namer.call` invocation into the flattening routine so that each member gets a unique name.

2023-09-28 16:02 UTC, teoxoy requested changes
Thanks for the PR! It looks good but could you add a test for this? The one in the issue would work.

2023-09-28 16:10 UTC, evahop commented
Yes, I was going to add that there's also a `namer.namespace` method specifically for structs, It may be more appropriate, but I am not familiar enough with result types. I will try to use that instead, but no promises.

2023-09-28 20:34 UTC, evahop commented
Added tests, including one that confirms #1464 has also been fixed (not by me).
Abandoned  `namer.namespace` since `built-ins` don't necessarily end up in the struct, 
I just added a new `namer` solely for the locations.

2023-09-28 21:04 UTC, evahop commented
Added snapshot, including one that confirms #1464 has also been fixed (not by me).
Abandoned  `namer.namespace` and just ended up just added a new `namer` solely for the locations. It causes a bit of duplication, since I also stick them in `flattened_member_names` if you want.

2023-09-28 21:05 UTC, evahop commented
Added snapshot, which also confirms #1464 has been fixed (not by me).
Abandoned  `namer.namespace` and ended up just added a new `namer` solely for the locations. It causes a bit of duplication, since I also stick them in `flattened_member_names` if you want.

2023-09-28 21:07 UTC, evahop commented
Added the snapshot, which also confirms #1464 has been fixed (not by me).
Abandoned  `namer.namespace` and ended up just adding a new `namer` solely for the locations.

2023-09-29 10:17 UTC, teoxoy commented on src/back/msl/writer.rs
> +                            );
```suggestion
                            let name_key = NameKey::StructMember(arg.ty, member_index);
                            let name = match member.binding {
                                Some(crate::Binding::Location { .. }) => {
                                    varyings_namer.call(&self.names[&name_key])
                                }
                                _ => self.namer.call(&self.names[&name_key]),
                            };
                            flattened_member_names.insert(name_key, name);
```

2023-09-29 10:19 UTC, teoxoy commented
Seems like https://github.com/gfx-rs/naga/issues/1464 was fixed by https://github.com/gfx-rs/naga/pull/1766.

2023-09-29 10:19 UTC, teoxoy approved these changes
Good stuff!

2023-09-29 10:26 UTC, merged