Don't use layout qualifiers to allow for GLSL 140 support
gfx-rs/naga pull request #2575
Opened 2023-10-20 17:19 UTC by Zoxc

This avoids emitting layout qualifiers for shader I/O to allow sufficient GLSL 140 support for the wgpu cube example. These must instead of bound by OpenGL code using the new `varying` field of `ReflectionInfo`.

Precision qualifiers are changed to only be emitted for ES.

2023-10-23 14:00 UTC, teoxoy requested changes
Looks good but can you update the ron files for:

- `interpolate`
- `bounds-check-image-rzsw`
- `bounds-check-image-restrict`

to target ES? I think it wasn't meant for them to target desktop GL.

2023-10-23 22:33 UTC, Zoxc commented
They all seem to use non-ES features.

2023-10-24 09:55 UTC, teoxoy commented
Ah, I see.

2023-10-24 09:55 UTC, teoxoy approved these changes

2023-10-24 09:56 UTC, merged